# Generated by Django 5.1.15 on 2026-06-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramplin', '0017_opportunity_company_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationlog',
            name='action',
            field=models.CharField(choices=[('approve_mentor', 'Одобрил заявку на менторство'), ('reject_mentor', 'Отклонил заявку на менторство'), ('approve_opportunity', 'Одобрил объявление'), ('reject_opportunity', 'Отклонил объявление'), ('delete_opportunity', 'Удалил объявление'), ('block_user', 'Заблокировал пользователя'), ('unblock_user', 'Разблокировал пользователя'), ('moderate_review', 'Модерировал отзыв')], max_length=50, verbose_name='Действие'),
        ),
    ]
