# Generated by Django 5.1.15 on 2026-06-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramplin', '0018_alter_moderationlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='contact_person_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email контактного лица'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя контактного лица'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='contact_person_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='contact_person_position',
            field=models.CharField(blank=True, max_length=150, verbose_name='Должность'),
        ),
    ]
